// Code generated by genx:uintstr DO NOT EDIT.
package uintstr

import (
	"strconv"
)

// UnmarshalText parse OrderID
func (v *OrderID) UnmarshalText(text []byte) error {
	s := string(text)
	if len(s) == 0 {
		return nil
	}
	d, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return err
	}
	*v = OrderID(d)
	return nil
}

// MarshalText serializes OrderID
func (v OrderID) MarshalText() (text []byte, err error) {
	if v == 0 {
		return nil, nil
	}
	return []byte(strconv.FormatUint(uint64(v), 10)), nil
}
