// Package testdata GENERATED BY code_error DO NOT EDIT
package testdata

import (
	"errors"
	"fmt"
)

func (e Code) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[testdata.Code:%d] unknown", e)
	case CODE_UNDEFINED:
		return "[testdata.Code:0] undefined"
	case CODE__ERROR1:
		return "[testdata.Code:1] error1 message"
	case CODE__ERROR2:
		return "[testdata.Code:2] error2 message"
	case CODE__ERROR3:
		return "[testdata.Code:3] ERROR3"
	}
}

func NewCodeError(code Code) error {
	return &CodeError{
		code: code,
	}
}

func NewCodeErrorf(code Code, msg string, args ...any) error {
	return &CodeError{
		code: code,
		msg:  msg,
		args: args,
	}
}

func NewCodeErrorWrap(code Code, cause error) error {
	if cause == nil {
		return nil
	}
	return &CodeError{
		code:  code,
		args:  []any{cause},
		cause: cause,
	}
}

func NewCodeErrorWrapf(code Code, cause error, msg string, args ...any) error {
	if cause == nil {
		return nil
	}
	return &CodeError{
		code:  code,
		msg:   msg,
		args:  append(args, cause),
		cause: cause,
	}
}

type CodeError struct {
	code  Code
	msg   string
	args  []any
	cause error
}

func (e *CodeError) Error() string {
	msg := e.code.Message()
	if len(e.msg) > 0 {
		msg += ". " + e.msg
	}
	if e.cause != nil {
		msg += ". [cause: %+v]"
	}
	return fmt.Sprintf(msg, e.args...)
}

func (e *CodeError) Code() Code {
	return e.code
}

func (e *CodeError) Is(err error) bool {
	var target *CodeError
	return errors.As(err, &target) && target.code == e.code
}

func (e *CodeError) Unwrap() error {
	return e.cause
}
