// Package testdata GENERATED BY code_error DO NOT EDIT
package testdata

import (
	"errors"
	"fmt"
)

func (e DomainCode) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[DOMAIN_NAME:%d] unknown", e)
	case DOMAIN_CODE_UNDEFINED:
		return "[DOMAIN_NAME:0] undefined"
	case DOMAIN_CODE__PARSE:
		return "[DOMAIN_NAME:1] parse failed"
	case DOMAIN_CODE__HANDLE:
		return "[DOMAIN_NAME:2] handle failed"
	case DOMAIN_CODE__PARAMETER:
		return "[DOMAIN_NAME:3] invalid parameter"
	}
}

func NewDomainCodeError(code DomainCode) error {
	return &DomainCodeError{
		code: code,
	}
}

func NewDomainCodeErrorf(code DomainCode, msg string, args ...any) error {
	return &DomainCodeError{
		code: code,
		msg:  msg,
		args: args,
	}
}

func NewDomainCodeErrorWrap(code DomainCode, cause error) error {
	if cause == nil {
		return nil
	}
	return &DomainCodeError{
		code:  code,
		args:  []any{cause},
		cause: cause,
	}
}

func NewDomainCodeErrorWrapf(code DomainCode, cause error, msg string, args ...any) error {
	if cause == nil {
		return nil
	}
	return &DomainCodeError{
		code:  code,
		msg:   msg,
		args:  append(args, cause),
		cause: cause,
	}
}

type DomainCodeError struct {
	code  DomainCode
	msg   string
	args  []any
	cause error
}

func (e *DomainCodeError) Error() string {
	msg := e.code.Message()
	if len(e.msg) > 0 {
		msg += ". " + e.msg
	}
	if e.cause != nil {
		msg += ". [cause: %+v]"
	}
	return fmt.Sprintf(msg, e.args...)
}

func (e *DomainCodeError) Code() DomainCode {
	return e.code
}

func (e *DomainCodeError) Is(err error) bool {
	var target *DomainCodeError
	return errors.As(err, &target) && target.code == e.code
}

func (e *DomainCodeError) Unwrap() error {
	return e.cause
}
