// Code generated by genx:doc DO NOT EDIT.
package docx

import (
	"github.com/xoctopus/x/docx"
)

func (v *Empty) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *S) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NameType":
			return []string{"NameType"}, true
		case "Interface":
			return []string{"Interface"}, true
		case "S":
			return []string{"S star expr"}, true
		case "T1":
			return []string{"T1 ext selector"}, true
		case "T2":
			return []string{"T2 star ref"}, true
		case "T3":
			return []string{"T3 index expr"}, true
		case "T4":
			return []string{"T4 star index expr"}, true
		case "T5":
			return []string{"T5 index list expr"}, true
		case "T6":
			return []string{"T6 star index expr"}, true
		case "NoDoc":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.D, "D ident only", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "S star expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "T1 ext selector", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "T2 star ref", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "T3 index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "T4 star index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "T5 index list expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "T6 star index expr", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"S struct"}, true
}

func (v *D) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "X":
			return []string{"X int"}, true
		case "Y":
			return []string{"Y string"}, true
		case "F":
			return []string{"F func"}, true
		}
		return []string{}, false
	}
	return []string{"D doc"}, true
}

func (v *F) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"F func"}, true
}

func (v *G[V]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NameType":
			return []string{"NameType"}, true
		case "Interface":
			return []string{"Interface"}, true
		case "S":
			return []string{"S star expr"}, true
		case "T1":
			return []string{"T1 ext selector"}, true
		case "T2":
			return []string{"T2 star ref"}, true
		case "T3":
			return []string{"T3 index expr"}, true
		case "T4":
			return []string{"T4 star index expr"}, true
		case "T5":
			return []string{"T5 // index list expr"}, true
		case "T6":
			return []string{"T6 // star index expr"}, true
		}
		if doc, ok := docx.Of(&v.D, "D ident only", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "S star expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "T1 ext selector", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "T2 star ref", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "T3 index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "T4 star index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "T5 // index list expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "T6 // star index expr", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}
