// Code generated by genx:doc DO NOT EDIT.
package docx

import (
	"github.com/xoctopus/x/docx"
)

func (v *Empty) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *S) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NameType":
			return []string{""}, true
		case "Interface":
			return []string{"NamedInterface"}, true
		case "S":
			return []string{"*SPrefix"}, true
		case "T1":
			return []string{"ext.T1Prefix"}, true
		case "T2":
			return []string{"*ext.T2Prefix"}, true
		case "T3":
			return []string{"ext.T3[int]Prefix"}, true
		case "T4":
			return []string{"*ext.T4[int]Prefix"}, true
		case "T5":
			return []string{"ext.T5[int,int]Prefix"}, true
		case "T6":
			return []string{"*ext.T6[int, int]Prefix"}, true
		case "NoDoc":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.D, "AnonymousDPrefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "*SPrefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "ext.T1Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "*ext.T2Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "ext.T3[int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "*ext.T4[int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "ext.T5[int,int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "*ext.T6[int, int]Prefix", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"struct"}, true
}

func (v *D) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "X":
			return []string{"int"}, true
		case "Y":
			return []string{"string"}, true
		case "F":
			return []string{"func"}, true
		}
		return []string{}, false
	}
	return []string{"doc"}, true
}

func (v *F) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"func"}, true
}

func (v *G[V]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NameType":
			return []string{""}, true
		case "Interface":
			return []string{""}, true
		case "S":
			return []string{"star expr"}, true
		case "T1":
			return []string{"ext selector"}, true
		case "T2":
			return []string{"star ref"}, true
		case "T3":
			return []string{"index expr"}, true
		case "T4":
			return []string{"star index expr"}, true
		case "T5":
			return []string{"index list expr"}, true
		case "T6":
			return []string{"star index list expr"}, true
		}
		if doc, ok := docx.Of(&v.D, "ident only", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "star expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "ext selector", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "star ref", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "star index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "index list expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "star index list expr", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}
