// Code generated by genx:doc@devel DO NOT EDIT.
package docx

import (
	"github.com/xoctopus/x/docx"
)

func (v *Empty) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{}, true
}

func (v *S) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "unexported":
			return []string{}, true
		case "Empty2":
			return []string{"Empty2Doc"}, true
		case "Inline":
			return []string{"InlineUnnamed"}, true
		case "NameType":
			return []string{}, true
		case "Interface":
			return []string{"NamedInterface"}, true
		case "NoDoc":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.D, "AnonymousDPrefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "*SPrefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "ext.T1Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "*ext.T2Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "ext.T3[int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "*ext.T4[int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "ext.T5[int,int]Prefix", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "*ext.T6[int, int]Prefix", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"struct"}, true
}

func (v *D) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "X":
			return []string{"int"}, true
		case "Y":
			return []string{"string"}, true
		case "F":
			return []string{"func"}, true
		}
		return []string{}, false
	}
	return []string{"doc"}, true
}

func (v *F) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		return []string{}, false
	}
	return []string{"func"}, true
}

func (v *G[V]) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NameType":
			return []string{}, true
		case "Interface":
			return []string{}, true
		}
		if doc, ok := docx.Of(&v.D, "ident only", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.S, "star expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T1, "ext selector", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T2, "star ref", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T3, "index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T4, "star index expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(&v.T5, "index list expr", names...); ok {
			return doc, true
		}

		if doc, ok := docx.Of(v.T6, "star index list expr", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *UserProfile) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Avatar":
			return []string{"URL"}, true
		}
		return []string{}, false
	}
	return []string{}, true
}

func (v *User) DocOf(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{"is the user's full name."}, true
		case "Age":
			return []string{"is the user's age in years."}, true
		}
		if doc, ok := docx.Of(&v.UserProfile, "user profile", names...); ok {
			return doc, true
		}
		return []string{}, false
	}
	return []string{"represents a system user."}, true
}
