// Code generated by genx:test_genx@ DO NOT EDIT.
package ignored

import (
	"bytes"

	"github.com/xoctopus/genx/testdata/errors"
)

var _ = Gender(1)
var _ = errors.New("some error")
var _ = bytes.NewBufferString("some string for bytes.Buffer")
