// Code generated by genx:enum@devel DO NOT EDIT.
package enumx

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[EnableStatus] = (*EnableStatus)(nil)

// ParseEnableStatus parse EnableStatus from key
func ParseEnableStatus(key string) (EnableStatus, error) {
	switch key {
	case "ENABLED", "Y":
		return ENABLE_STATUS__ENABLED, nil
	case "DISABLED", "N":
		return ENABLE_STATUS__DISABLED, nil
	default:
		var v EnableStatus
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return ENABLE_STATUS_UNKNOWN, enumx.ParseErrorFor[EnableStatus](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (EnableStatus) EnumValues() []any {
	return []any{
		ENABLE_STATUS__ENABLED,
		ENABLE_STATUS__DISABLED,
	}
}

// Values returns enum value list of EnableStatus
func (EnableStatus) Values() []EnableStatus {
	return []EnableStatus{
		ENABLE_STATUS__ENABLED,
		ENABLE_STATUS__DISABLED,
	}
}

// String returns v's string as key
func (v EnableStatus) String() string {
	switch v {
	case ENABLE_STATUS__ENABLED:
		return "Y"
	case ENABLE_STATUS__DISABLED:
		return "N"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v EnableStatus) Text() string {
	switch v {
	case ENABLE_STATUS__ENABLED:
		return "开启"
	case ENABLE_STATUS__DISABLED:
		return "关闭"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v EnableStatus) IsZero() bool {
	return v == ENABLE_STATUS_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v EnableStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *EnableStatus) UnmarshalText(data []byte) error {
	vv, err := ParseEnableStatus(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v EnableStatus) Value() (driver.Value, error) {
	return v.String(), nil
}

// Scan implements sql.Scanner
func (v *EnableStatus) Scan(src any) error {
	var data []byte
	switch x := src.(type) {
	case string:
		data = []byte(x)
	case []byte:
		data = x
	default:
		return fmt.Errorf("cannot scan %T value from `%T`", v, x)
	}
	return v.UnmarshalText(data)
}
