// Code generated by genx:enum@devel DO NOT EDIT.
package enumx

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[ProductType] = (*ProductType)(nil)

// ParseProductType parse ProductType from key
func ParseProductType(key string) (ProductType, error) {
	switch key {
	case "MEN_CLOTH":
		return PRODUCT_TYPE__MEN_CLOTH, nil
	case "SMART_PHONE":
		return PRODUCT_TYPE__SMART_PHONE, nil
	default:
		var v ProductType
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return PRODUCT_TYPE_UNKNOWN, enumx.ParseErrorFor[ProductType](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (ProductType) EnumValues() []any {
	return []any{
		PRODUCT_TYPE__MEN_CLOTH,
		PRODUCT_TYPE__SMART_PHONE,
	}
}

// Values returns enum value list of ProductType
func (ProductType) Values() []ProductType {
	return []ProductType{
		PRODUCT_TYPE__MEN_CLOTH,
		PRODUCT_TYPE__SMART_PHONE,
	}
}

// String returns v's string as key
func (v ProductType) String() string {
	switch v {
	case PRODUCT_TYPE__MEN_CLOTH:
		return "MEN_CLOTH"
	case PRODUCT_TYPE__SMART_PHONE:
		return "SMART_PHONE"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v ProductType) Text() string {
	switch v {
	case PRODUCT_TYPE__MEN_CLOTH:
		return "男装"
	case PRODUCT_TYPE__SMART_PHONE:
		return "智能手机"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v ProductType) IsZero() bool {
	return v == PRODUCT_TYPE_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v ProductType) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *ProductType) UnmarshalText(data []byte) error {
	vv, err := ParseProductType(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Category describes ProductCategory attribute
func (v ProductType) Category() ProductCategory {
	switch v {
	case PRODUCT_TYPE__MEN_CLOTH:
		return ProductCategory(PRODUCT_CATEGORY__CLOTHING)
	case PRODUCT_TYPE__SMART_PHONE:
		return ProductCategory(PRODUCT_CATEGORY__3C)
	default:
		return *new(ProductCategory)
	}
}

// Value implements driver.Valuer
func (v ProductType) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *ProductType) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = ProductType(i)
	return nil
}
