// Code generated by genx:enum@devel DO NOT EDIT.
package enumx

import (
	"bytes"
	"database/sql/driver"
	"fmt"

	"github.com/xoctopus/x/enumx"
)

var _ enumx.Enum[ProductCategory] = (*ProductCategory)(nil)

// ParseProductCategory parse ProductCategory from key
func ParseProductCategory(key string) (ProductCategory, error) {
	switch key {
	case "CLOTHING":
		return PRODUCT_CATEGORY__CLOTHING, nil
	case "3C":
		return PRODUCT_CATEGORY__3C, nil
	default:
		var v ProductCategory
		if _, err := fmt.Sscanf(key, "UNKNOWN_%d", &v); err != nil {
			return v, nil
		}
		return PRODUCT_CATEGORY_UNKNOWN, enumx.ParseErrorFor[ProductCategory](key)
	}
}

// EnumValues implements enumx.CanBeEnum
func (ProductCategory) EnumValues() []any {
	return []any{
		PRODUCT_CATEGORY__CLOTHING,
		PRODUCT_CATEGORY__3C,
	}
}

// Values returns enum value list of ProductCategory
func (ProductCategory) Values() []ProductCategory {
	return []ProductCategory{
		PRODUCT_CATEGORY__CLOTHING,
		PRODUCT_CATEGORY__3C,
	}
}

// String returns v's string as key
func (v ProductCategory) String() string {
	switch v {
	case PRODUCT_CATEGORY__CLOTHING:
		return "CLOTHING"
	case PRODUCT_CATEGORY__3C:
		return "3C"
	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

// Text returns the description as for human reading
func (v ProductCategory) Text() string {
	switch v {
	case PRODUCT_CATEGORY__CLOTHING:
		return "服饰"
	case PRODUCT_CATEGORY__3C:
		return "3C数码"
	default:
		return v.String()
	}
}

// IsZero checks if v is zero
func (v ProductCategory) IsZero() bool {
	return v == PRODUCT_CATEGORY_UNKNOWN
}

// MarshalText implements encoding.TextMarshaler
func (v ProductCategory) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (v *ProductCategory) UnmarshalText(data []byte) error {
	vv, err := ParseProductCategory(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

// Value implements driver.Valuer
func (v ProductCategory) Value() (driver.Value, error) {
	offset := 0
	if drv, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = drv.Offset()
	}
	return int64(v) + int64(offset), nil
}

// Scan implements sql.Scanner
func (v *ProductCategory) Scan(src any) error {
	offset := 0
	if offsetter, ok := any(v).(enumx.DriverValueOffset); ok {
		offset = offsetter.Offset()
	}
	i, err := enumx.Scan(src, offset)
	if err != nil {
		return err
	}
	*v = ProductCategory(i)
	return nil
}
