package snippet

import (
	"fmt"
)

func Poster(pkg string, generator string) Snippet {
	return Block(fmt.Sprintf(""+
		"// Package %s GENERATED BY %s DO NOT EDIT\n"+
		"package %s\n\n",
		pkg, generator, pkg,
	))
}
