// Code generated by genx:code@devel DO NOT EDIT.
package testdata

import (
	"fmt"
)

func (e Code) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[TESTDATA::CODE:%d] unknown", e)
	case CODE_UNDEFINED:
		return "[TESTDATA::CODE:0] undefined"
	case CODE__ERROR1:
		return "[TESTDATA::CODE:1] error1 message"
	case CODE__ERROR2:
		return "[TESTDATA::CODE:2] error2 message"
	case CODE__ERROR3:
		return "[TESTDATA::CODE:3] ERROR3"
	}
}
