// Package testdata GENERATED BY errx_code DO NOT EDIT
package testdata

import (
	"fmt"
)

func (e DomainCode) Message() string {
	switch e {
	default:
		return fmt.Sprintf("[DOMAIN_NAME:%d] unknown", e)
	case DOMAIN_CODE_UNDEFINED:
		return "[DOMAIN_NAME:0] undefined"
	case DOMAIN_CODE__PARSE:
		return "[DOMAIN_NAME:1] parse failed"
	case DOMAIN_CODE__HANDLE:
		return "[DOMAIN_NAME:2] handle failed"
	case DOMAIN_CODE__PARAMETER:
		return "[DOMAIN_NAME:3] invalid parameter"
	}
}
