package snippet

import (
	"fmt"
)

func Poster(pkg string, generator, version string) Snippet {
	// https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
	// Code generated .* DO NOT EDIT\.$
	return Block(fmt.Sprintf(""+
		"// Code generated by %s@%s DO NOT EDIT.\n"+
		"package %s\n\n",
		generator, version, pkg,
	))
}
