package snippet_test

import (
	"bufio"
	"bytes"
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"go/types"
	"hash"
	"io"
	"iter"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"sync"
	"testing"

	. "github.com/xoctopus/genx/pkg/snippet"
	. "github.com/xoctopus/x/testx"

	_ "embed"
	_ "github.com/xoctopus/x/ptrx"

	"github.com/xoctopus/typx/pkg/typx"
	"github.com/xoctopus/x/misc/must"
	"github.com/xoctopus/x/ptrx"

	"github.com/xoctopus/genx/internal/dumper"
	"github.com/xoctopus/genx/testdata"
)

func Print(ctx context.Context, ss ...Snippet) {
	Write(ctx, os.Stdout, ss...)
}

func Write(ctx context.Context, w io.Writer, ss ...Snippet) {
	for _, s := range ss {
		if !IsNil(s) {
			for line := range s.Fragments(ctx) {
				if line == eof {
					break
				}
				_, _ = w.Write([]byte(line))
			}
		}
	}
}

func ExampleComments() {
	Print(
		context.Background(),
		Snippets(
			NewLine(1),
			Document("TypeName", "this is a document for TypeName.", " line1\n line2\n line3"),
			Comments("\n", ""), // empty skipped
			InlineComment("this is an inline comment"),
			Directive("generate", "arg1", "\n", "arg2", "\t", "--flag"),
		),
	)

	// Output:
	// // TypeName this is a document for TypeName.
	// // line1
	// // line2
	// // line3
	// // this is an inline comment
	// //go:generate arg1 arg2 --flag
}

func ExampleBlock() {
	Print(
		context.Background(),
		Document("F", "this is a document for F."),
		NewLine(1),
		Block("func F() string {"),
		NewLine(1),
		Indent(1), BlockF("x := "), BlockRaw("abc"),
		NewLine(1),
		Indent(1), Block("return x"),
		NewLine(1),
		Block("}"), NewLine(1),
	)

	// Output:
	// // F this is a document for F.
	// func F() string {
	// 	x := "abc"
	// 	return x
	// }
	//
}

func ExampleIdentFor() {
	ctx := dumper.WithEntry(context.Background(), "github.com/xoctopus/genx/testdata")

	body := Snippets(
		NewLine(1),
		IdentFor[string](ctx),
		IdentOf(ctx, bytes.Reader{}),
		IdentFor[bytes.Reader](ctx),
		IdentFor[*bytes.Buffer](ctx),
		IdentFor[io.Reader](ctx),
		IdentFor[dumper.Import](ctx),
		IdentRT(ctx, reflect.TypeFor[float64]()),
		IdentTT(ctx, types.Typ[types.Int32]),
	)

	Print(
		ctx,
		Poster("demo", "genx:test_ident"),
		Imports(ctx),
		body,
	)

	// Output:
	// // Code generated by genx:test_ident DO NOT EDIT.
	// package demo
	//
	// import (
	// 	"bytes"
	// 	"io"
	//
	// 	"github.com/xoctopus/genx/internal/dumper"
	// )
	//
	// string
	// bytes.Reader
	// bytes.Reader
	// *bytes.Buffer
	// io.Reader
	// dumper.Import
	// float64
	// int32
}

func ExampleExpose() {
	ctx := dumper.WithEntry(context.Background(), "github.com/xoctopus/genx/testdata")

	pkg := dumper.Load(ctx, "github.com/xoctopus/genx/testdata")

	t1 := pkg.Types.Scope().Lookup("T").Type().(*types.Named)
	t2 := pkg.Types.Scope().Lookup("TT").Type().(*types.Named)
	t3 := pkg.Types.Scope().Lookup("DemoEnum").Type().(*types.Named)

	body := Snippets(
		NewLine(1),
		// imported: project
		Expose(ctx, "github.com/xoctopus/genx/testdata", "FuncT", IdentFor[string](ctx)),
		ExposeUnsafe(ctx, "github.com/xoctopus/genx/testdata", "FuncT"),
		Expose(ctx, "github.com/xoctopus/genx/testdata", "DEMO_ENUM_A"),
		Expose(ctx, "github.com/xoctopus/genx/testdata", "Var"),
		Expose(ctx, "github.com/xoctopus/genx/testdata", "VarFuncT"),
		ExposeObject(ctx, t1.Obj(), IdentFor[int](ctx)),
		ExposeObject(ctx, t2.Obj(), IdentFor[int](ctx), IdentFor[string](ctx)),
		ExposeObjectUnsafe(ctx, t3.Obj()),
		// imported: std
		Expose(ctx, "fmt", "Sscanf"),
		Expose(ctx, "io", "ReadAll"),
		// imported: general
		Expose(ctx, "errors", "New"),
		Expose(ctx, "github.com/xoctopus/x/ptrx", "Ptr", IdentFor[testdata.DemoEnum](ctx)),
	)

	Print(
		ctx,
		Poster("demo", "genx:test_expose"),
		Imports(ctx),
		body,
	)

	// Output:
	// // Code generated by genx:test_expose DO NOT EDIT.
	// package demo
	//
	// import (
	// 	"errors"
	// 	"fmt"
	// 	"io"
	//
	// 	"github.com/xoctopus/x/ptrx"
	// )
	//
	// FuncT[string]
	// FuncT
	// DEMO_ENUM_A
	// Var
	// VarFuncT
	// T[int]
	// TT[int, string]
	// DemoEnum
	// fmt.Sscanf
	// io.ReadAll
	// errors.New
	// ptrx.Ptr[DemoEnum]
}

//go:embed testdata/enumx.go.tpl
var template []byte

func ExampleTemplate() {
	ctx := dumper.WithEntry(
		context.Background(),
		"github.com/xoctopus/genx/testdata",
	)

	tpl := Template(
		bytes.NewReader(template),
		ArgFor[testdata.Gender](ctx, "Type"),
		ArgExpose(ctx, "fmt", "Sprintf"),
		Arg(ctx, "NameToValueCases", Snippets(
			NewLine(1),
			Compose(Indent(1), Block(`case "MALE":`)),
			Compose(Indent(2), Block(`return GENDER__MALE, nil`)),
			Compose(Indent(1), Block(`case "FEMALE":`)),
			Compose(Indent(2), Block(`return GENDER__FEMALE, nil`)),
		)),
		ArgExpose(ctx, "github.com/xoctopus/genx/testdata", "GENDER_UNKNOWN").
			WithName("UnknownValue"),
		ArgExpose(ctx, "errors", "New"),
		Arg(ctx, "Values", Snippets(
			NewLine(1),
			Compose(Indent(2), Expose(ctx, "github.com/xoctopus/genx/testdata", "GENDER__MALE"), Block(",")),
			Compose(Indent(2), Expose(ctx, "github.com/xoctopus/genx/testdata", "GENDER__FEMALE"), Block(",")),
		)),
		ArgExpose(ctx, "github.com/xoctopus/genx/testdata", "Scan").WithName("EnumScanBrick"),
		ArgExposeUnsafe(ctx, "bytes", "ToUpper"),
		ArgExpose(ctx, "fmt", "Sscanf"),
		ArgT[driver.Value](ctx),
		Arg(ctx, "ValueToDescCases", Snippets(
			NewLine(1),
			Compose(Indent(1), Block(`case GENDER__MALE:`)),
			Compose(Indent(2), Block(`return "男"`)),
			Compose(Indent(1), Block(`case GENDER__FEMALE:`)),
			Compose(Indent(2), Block(`return "女"`)),
		)),
		Arg(ctx, "ValueToNameCases", Snippets(
			NewLine(1),
			Compose(Indent(1), Block(`case GENDER__MALE:`)),
			Compose(Indent(2), Block(`return "MALE"`)),
			Compose(Indent(1), Block("case GENDER__FEMALE:")),
			Compose(Indent(2), Block(`return "FEMALE"`)),
		)),
		nil,
		Arg(ctx, "Nil", nil),
	)

	b := bytes.NewBuffer(nil)

	Write(
		ctx,
		b,
		Poster("testdata", "genx:test_template"),
		Imports(ctx),
		tpl,
	)

	filename := filepath.Join(must.NoErrorV(os.Getwd()), "..", "..", "testdata", "gender_genx_tpl_test_enum.go")
	must.NoError(os.RemoveAll(filename))
	output, _ := os.OpenFile(
		filename,
		os.O_WRONLY|os.O_CREATE|os.O_TRUNC,
		0o644,
	)
	_, _ = io.Copy(output, b)
	_ = output.Sync()
	_ = output.Close()

	// Output:
}

func ExampleValue() {
	ctx := dumper.WithEntry(
		context.Background(),
		"github.com/xoctopus/genx/pkg/snippet_test",
	)

	body := Snippets(
		NewLine(1),
		Value(ctx, 1),
		Value(ctx, int8(1)),
		Value(ctx, uintptr(100)),
		Value(ctx, 1.1),
		Value(ctx, float32(1.1)),
		Value(ctx, "10"),
		Value(ctx, testdata.String("10")),
		Value(ctx, func() {}),
		Value(ctx, testdata.Gender(1)),
		Value(ctx, testdata.Struct{
			A: 100,
			B: &testdata.Struct{A: 101},
		}),
		Value(ctx, struct {
			X int `json:"x,omitzero"`
		}{0}),
		Value(ctx, map[int]int{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}),
		Value(ctx, map[any]int{
			nil:                  0,
			(*int)(nil):          1,
			"1":                  2,
			"3":                  3,
			"5":                  4,
			testdata.String("2"): 5,
			testdata.String("4"): 6,
			testdata.String("6"): 7,
		}),
		Value(ctx, []map[any]any{{
			testdata.String("0"):           3, // snippet_test.String  3
			"1":                            2, // string               2
			2:                              0, // int                  0
			ptrx.Ptr(testdata.String("3")): 1, // pointer              1
		}}),
		Value(ctx, []any{nil, true, false, complex64(1), complex128(1)}),
		Value(ctx, nil),
	)

	Print(
		ctx,
		Poster("demo", "genx:test_value"),
		Imports(ctx),
		body,
	)

	// Output:
	// // Code generated by genx:test_value DO NOT EDIT.
	// package demo
	//
	// import (
	// 	"github.com/xoctopus/x/ptrx"
	//
	// 	"github.com/xoctopus/genx/testdata"
	// )
	//
	// 1
	// 1
	// 100
	// 1.1
	// 1.1
	// "10"
	// testdata.String("10")
	// testdata.Gender(1)
	// testdata.Struct{A: 100, B: ptrx.Ptr[testdata.Struct](testdata.Struct{A: 101, B: nil})}
	// struct { X int "json:\"x,omitzero\"" }{X: 0}
	// map[int]int{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
	// map[interface {}]int{nil: 0, nil: 1, "1": 2, "3": 3, "5": 4, testdata.String("2"): 5, testdata.String("4"): 6, testdata.String("6"): 7}
	// []map[interface {}]interface {}{map[interface {}]interface {}{2: 0, ptrx.Ptr[testdata.String](testdata.String("3")): 1, "1": 2, testdata.String("0"): 3}}
	// []interface {}{nil, true, false, (1+0i), (1+0i)}
	// nil
}

var eof = strconv.QuoteRune(-1)

func ExampleSnippets_eof() {
	Print(context.Background(), Compose(Block(eof)))
	Print(context.Background(), &Placeholder{})

	// Output:
}

func ExampleStrings() {
	Print(context.Background(), Strings(",", "\n", "1", "2", "3", "4"))
	Print(context.Background(), Strings(",", "\n"))

	// Output:
	// "1",
	// "2",
	// "3",
	// "4",
}

type (
	StructT[T any, E any] struct {
		_            *StructT[int, string]
		bufio.Reader // bufio package will be ignored by tracker
	}
	F[IN any, OUT any]       func(IN) (OUT, error)
	Map[K comparable, V any] map[K]V
)

func TestTracker_InIdent_GenericTypeParameters(t *testing.T) {
	entry := "github.com/xoctopus/genx/pkg/snippet"
	imp := dumper.NewImportTracker(entry)
	ctx := dumper.With(context.Background(), imp)

	// generic value
	IdentOf(ctx, testdata.T[fmt.Stringer]{})
	// generic type
	IdentFor[testdata.T[net.Addr]](ctx)
	// generic recursive
	IdentRT(ctx, reflect.TypeFor[iter.Seq2[
		string,
		testdata.T[StructT[
			bytes.Buffer,
			*StructT[io.Reader, *url.URL],
		]]]]())
	// unnamed struct pointer
	tt := typx.NewRType(reflect.TypeFor[*struct {
		_ hash.Hash
		f F[*sync.Map, sort.Float64Slice]
	}]())
	Ident(ctx, tt)
	// has key and element
	IdentFor[Map[testdata.Gender, any]](ctx)
	// function
	f := func(int) string { return "" }
	IdentOf(ctx, f)
	IdentFor[interface {
		Apply(*sql.DB) error
		New(string) (*sql.DB, error)
	}](ctx)

	imp.Init()

	Expect(t, imp.PackageName(entry), Equal(""))

	Expect(t, imp.PackageName("fmt"), NotEqual(""))
	Expect(t, imp.PackageName("net"), NotEqual(""))
	Expect(t, imp.PackageName("iter"), NotEqual(""))
	Expect(t, imp.PackageName("github.com/xoctopus/genx/testdata"), NotEqual(""))
	Expect(t, imp.PackageName("github.com/xoctopus/genx/pkg/snippet_test"), NotEqual(""))
	Expect(t, imp.PackageName("bytes"), NotEqual(""))
	Expect(t, imp.PackageName("io"), NotEqual(""))
	Expect(t, imp.PackageName("net/url"), NotEqual(""))
	Expect(t, imp.PackageName("hash"), NotEqual(""))
	Expect(t, imp.PackageName("sync"), NotEqual(""))
	Expect(t, imp.PackageName("sort"), NotEqual(""))
	Expect(t, imp.PackageName("database/sql"), NotEqual(""))
	// named struct field will be skipped
	ExpectPanic(
		t,
		func() { imp.PackageName("bufio") },
		ErrorContains("imported package bufio not be tracked"),
	)
}
