// Code generated by genx:context@devel DO NOT EDIT.
package contextx

import (
	"context"
	"net"

	"github.com/xoctopus/x/contextx"
)

type tCtxT struct{}

var (
	TFrom  = contextx.From[tCtxT, T]
	WithT  = contextx.With[tCtxT, T]
	MustT  = contextx.Must[tCtxT, T]
	CarryT = contextx.Carry[tCtxT, T]
)

type tCtxTT struct{}

var (
	TTFrom  = contextx.From[tCtxTT, TT]
	WithTT  = contextx.With[tCtxTT, TT]
	MustTT  = contextx.Must[tCtxTT, TT]
	CarryTT = contextx.Carry[tCtxTT, TT]
)

type tCtxTargs[T interface{}] struct{}

// TargsFrom try extract Targs from context
func TargsFrom[T interface{}](ctx context.Context) (Targs[T], bool) {
	return contextx.From[tCtxTargs[T], Targs[T]](ctx)
}

// MustTargs asserts Targs from context
func MustTargs[T interface{}](ctx context.Context) Targs[T] {
	return contextx.Must[tCtxTargs[T], Targs[T]](ctx)
}

// WithTargs inject Targs to context
func WithTargs[T interface{}](ctx context.Context, v Targs[T]) context.Context {
	return contextx.With[tCtxTargs[T], Targs[T]](ctx, v)
}

// CarryTargs returns Targs context carrier
func CarryTargs[T interface{}](v Targs[T]) contextx.Carrier {
	return contextx.Carry[tCtxTargs[T], Targs[T]](v)
}

type tCtxGeneric[T net.Addr] struct{}

// GenericFrom try extract Generic from context
func GenericFrom[T net.Addr](ctx context.Context) (Generic[T], bool) {
	return contextx.From[tCtxGeneric[T], Generic[T]](ctx)
}

// MustGeneric asserts Generic from context
func MustGeneric[T net.Addr](ctx context.Context) Generic[T] {
	return contextx.Must[tCtxGeneric[T], Generic[T]](ctx)
}

// WithGeneric inject Generic to context
func WithGeneric[T net.Addr](ctx context.Context, v Generic[T]) context.Context {
	return contextx.With[tCtxGeneric[T], Generic[T]](ctx, v)
}

// CarryGeneric returns Generic context carrier
func CarryGeneric[T net.Addr](v Generic[T]) contextx.Carrier {
	return contextx.Carry[tCtxGeneric[T], Generic[T]](v)
}
