// Code generated by genx:ctx@(devel) DO NOT EDIT.
package contextx

import (
	"github.com/xoctopus/x/contextx"
)

type tCtxT struct{}

var (
	TFrom  = contextx.From[tCtxT, T]
	WithT  = contextx.With[tCtxT, T]
	MustT  = contextx.Must[tCtxT, T]
	CarryT = contextx.Carry[tCtxT, T]
)

type tCtxTT struct{}

var (
	TTFrom  = contextx.From[tCtxTT, TT]
	WithTT  = contextx.With[tCtxTT, TT]
	MustTT  = contextx.Must[tCtxTT, TT]
	CarryTT = contextx.Carry[tCtxTT, TT]
)
