// Package testdata GENERATED BY test_genx DO NOT EDIT
package testdata

import (
	"bytes"

	"github.com/pkg/errors"
)

var _ = Gender(1)
var _ = errors.New("some error")
var _ = bytes.NewBufferString("some string for bytes.Buffer")
